// src/routes/edit/share-options/exports/frameworks/angular-fragment.ts
import { format as formatPrettier, Options } from 'prettier';
import parserBabel from 'prettier/parser-babel';
import parserHtml from 'prettier/parser-html';
import parserCss from 'prettier/parser-postcss';
import { useContext } from 'react';
import { GlobalStateContext } from '../../../../../context';
import { allComponents } from '../../../../../fragment-components';
import { getAllFragmentStyleClasses } from '../../../../../ui-fragment/src/utils';
import { classNameFromFragment, hasFragmentStyleClasses, tagNameFromFragment } from '../../../../../utils/fragment-tools';
import { sortedUniq } from 'lodash';

const format = (source: string, options?: Options | undefined) => {
	// we're catching and ignorring errors so live editing doesn't throw errors
	try {
		return formatPrettier(source, options);
	} catch (_) {
		return source;
	}
};

const formatOptionsTypescript: Options = {
	plugins: [parserBabel],
	trailingComma: 'none',
	useTabs: true,
	parser: 'babel-ts'
};

const formatOptionsHtml: Options = {
	plugins: [parserHtml],
	trailingComma: 'none',
	useTabs: true,
	parser: 'html'
};

const formatOptionsCss: Options = {
	parser: 'css',
	plugins: [parserCss]
};

const addIfNotExist = (arr: any[], items: string[] | undefined) => {
	items?.forEach(item => {
		if (!arr.includes(item)) {
			arr.push(item);
		}
	});
	return arr;
};

const jsonToAngularImports = (json: any) => {
	const imports: any[] = [];

	for (const component of Object.values(allComponents)) {
		if (json.type === component.componentInfo.type) {
			addIfNotExist(imports, component.componentInfo.codeExport.angular?.imports);
		}
	}

	if (json.items) {
		json.items.forEach((item: any) => {
			addIfNotExist(imports, jsonToAngularImports(item));
		});
	}

	return imports;
};

const getAngularInputsFromJson = (json: any): string => {
	const getOne = (json: any) => {
		for (const component of Object.values(allComponents)) {
			if (json.type === component.componentInfo.type) {
				return component.componentInfo.codeExport.angular?.inputs({ json }) || '';
			}
		}
		return '';
	};

	return `${getOne(json)} ${json.items ? json.items.map((item: any) => getAngularInputsFromJson(item)).join('\n') : ''}
	`;
};

const getAngularOutputsFromJson = (json: any): string => {
	const getOne = (json: any) => {
		for (const component of Object.values(allComponents)) {
			if (json.type === component.componentInfo.type) {
				return component.componentInfo.codeExport.angular?.outputs({ json }) || '';
			}
		}
		return '';
	};

	return `${getOne(json)} ${json.items ? json.items.map((item: any) => getAngularOutputsFromJson(item)).join('\n') : ''}
	`;
};

export const jsonToTemplate = (json: any, fragments: any[]) => {
	if (typeof json === 'string' || !json) {
		return json;
	}

	for (const component of Object.values(allComponents)) {
		if (json.type === component.componentInfo.type && !component.componentInfo.codeExport.angular.isNotDirectExport) {
			return component.componentInfo.codeExport.angular.code({ json, jsonToTemplate, fragments });
		}
	}

	if (json.items) {
		return json.items.map((item: any) => jsonToTemplate(item, fragments)).join('\n');
	}
};

const getAllSubfragments = (json: any, fragments: any[]) => {
	let sharedComponents: any = {};

	if (json.type === 'fragment') {
		const fragment = fragments.find(f => f.id === json.fragmentId);

		sharedComponents[tagNameFromFragment(fragment)] = fragment;

		sharedComponents = {
			...sharedComponents,
			...getAllSubfragments(fragment.data, fragments)
		};
	}

	json.items?.forEach((item: any) => {
		sharedComponents = {
			...sharedComponents,
			...getAllSubfragments(item, fragments)
		};
	});

	return sharedComponents;
};

const getOtherImportModules = (input: any) => {
	if (input) {
		let imports: any = [];
		const regex = /(?<=import).*?(?=from)/gm;
		if (input.match(regex)) {
			imports = input.match(regex);
			imports = imports?.map((item: any) => item.replace(/[ }{]/g, '')).toString();
			imports = imports.split(',');
		}
		return imports;
	}
};

const otherImportsFromComponentObj = (json: any, fragments?: any[]) => {
	let imports = '';
	for (const component of Object.values(allComponents)) {
		if (json.type === component.componentInfo.type && component.componentInfo.codeExport.angular.otherImports) {
			imports += component.componentInfo.codeExport.angular.otherImports({ json });
			break;
		}
	}
	if (json.items) {
		imports += json.items.map((item: any) => otherImportsFromComponentObj(item, fragments)).join('\n');
	}

	// remove duplicate imports
	imports = sortedUniq(imports.split('\n')).join('\n');
	return imports;
};

const getComponentCode = (fragment: any, fragments: any[]) => {
	const componentCode: any = {};
	// eslint-disable-next-line react-hooks/rules-of-hooks
	const { styleClasses: globalStyleClasses } = useContext(GlobalStateContext);
	const subFragments = getAllSubfragments(fragment.data, fragments);

	// component.ts
	componentCode[`src/app/components/${tagNameFromFragment(fragment)}/${tagNameFromFragment(fragment)}.component.ts`] = format(
		`import { Component, Input, Output, EventEmitter } from '@angular/core';
		@Component({
			selector: 'app-${tagNameFromFragment(fragment)}',
			templateUrl: './${tagNameFromFragment(fragment)}.component.html'${hasFragmentStyleClasses(fragment) ? `,
			styleUrls: ['./${tagNameFromFragment(fragment)}.component.scss']` : ''}
		})
		export class ${classNameFromFragment(fragment)} {
			${getAngularInputsFromJson(fragment.data)}
			${getAngularOutputsFromJson(fragment.data)}
		}
	`, formatOptionsTypescript);

	// component.html
	componentCode[`src/app/components/${tagNameFromFragment(fragment)}/${tagNameFromFragment(fragment)}.component.html`] =
		format(jsonToTemplate(fragment.data, fragments), formatOptionsHtml);
	// module.ts
	componentCode[`src/app/components/${tagNameFromFragment(fragment)}/${tagNameFromFragment(fragment)}.module.ts`] = format(
		`import { NgModule } from "@angular/core";
		import { ${jsonToAngularImports(fragment.data).join(', ')} } from 'carbon-components-angular';
		import { ${classNameFromFragment(fragment)} } from "./${tagNameFromFragment(fragment)}.component";
		${otherImportsFromComponentObj(fragment.data, fragments)}
		${
			Object.values(subFragments).map((f) =>
				`import { ${classNameFromFragment(f)}Module} from "../${tagNameFromFragment(f)}/${tagNameFromFragment(f)}.module";`).join('\n')
		}

		@NgModule({
			imports: [${[
				...jsonToAngularImports(fragment.data),
				getOtherImportModules(otherImportsFromComponentObj(fragment.data, fragments)),
				...Object.values(subFragments).map((fragment) => `${classNameFromFragment(fragment)}Module`)
			].join(', ')}],
			declarations: [${classNameFromFragment(fragment)}],
			exports: [${classNameFromFragment(fragment)}]
		})
		export class ${classNameFromFragment(fragment)}Module {}
	`, formatOptionsTypescript);

	// component.scss
	componentCode[`src/app/components/${tagNameFromFragment(fragment)}/${tagNameFromFragment(fragment)}.component.scss`] = format(
		`${getAllFragmentStyleClasses(fragment, [], globalStyleClasses).map((styleClass: any) => {
			if (!styleClass.content || !styleClass.content.trim()) {
				return null;
			}

			return `.${styleClass.id} {
				${styleClass.content}
			}`;
		}).join('\n')}`,
		formatOptionsCss
	);
	return componentCode;
};

const getAllComponentsCode = (json: any, fragments: any[]) => {
	let allComponents: any = {};

	if (json.data) {
		allComponents = {
			...allComponents,
			...getComponentCode(json, fragments),
			...getAllComponentsCode(json.data, fragments)
		};
	}

	if (json.type === 'fragment') {
		const fragment = fragments.find(f => f.id === json.fragmentId);

		allComponents = {
			...allComponents,
			...getComponentCode(fragment, fragments),
			...getAllComponentsCode(fragment.data, fragments)
		};
	}

	json.items?.forEach((item: any) => {
		allComponents = {
			...allComponents,
			...getAllComponentsCode(item, fragments)
		};
	});

	return allComponents;
};

export const createAngularApp = (fragment: any, fragments: any[]) => {
	const tagName = tagNameFromFragment(fragment);
	const className = classNameFromFragment(fragment);

	const allComponents = getAllComponentsCode(fragment, fragments);

	const appComponentHtml =
		`<app-${tagName}></app-${tagName}>
		`;

	const appComponentTs =
		`import { Component } from '@angular/core';
		@Component({
			selector: 'app-root',
			templateUrl: './app.component.html'
		})
		export class AppComponent {
		}
		`;

	const appModule =
		`import { NgModule } from '@angular/core';
		import { BrowserModule } from '@angular/platform-browser';
		import { AppComponent } from './app.component';
		import { ${className}Module } from './components/${tagName}/${tagName}.module';

		@NgModule({
			imports: [BrowserModule, ${className}Module],
			declarations: [AppComponent],
			bootstrap: [AppComponent]
		})
		export class AppModule {}
		`;

	const indexHtml =
		`<!DOCTYPE html>
		<html lang='en'>
			<head>
				<meta charset='utf-8' />
				<title>Angular</title>
			</head>
			<body>
				<app-root></app-root>
			</body>
		</html>
		`;

	const mainTs =
		`import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
		import { AppModule } from './app/app.module';

		import "carbon-components/css/carbon-components.min.css";

		platformBrowserDynamic()
			.bootstrapModule(AppModule)
			.catch(err => console.log(err));
		`;

	const angularCliJson =
		`{
	"apps": [
		{
			"root": "src",
			"outDir": "dist",
			"assets": ["assets", "favicon.ico"],
			"index": "index.html",
			"main": "main.ts",
			"polyfills": "polyfills.ts",
			"prefix": "app",
			"styles": ["styles.scss"],
			"scripts": [],
			"environmentSource": "environments/environment.ts",
			"environments": {
				"dev": "environments/environment.ts",
				"prod": "environments/environment.prod.ts"
			}
		}
	]
}
`;

	const packageJson = {
		dependencies: {
			'@angular/animations': '12.2.0',
			'@angular/common': '12.2.0',
			'@angular/compiler': '12.2.0',
			'@angular/core': '12.2.0',
			'@angular/forms': '12.2.0',
			'@angular/platform-browser': '12.2.0',
			'@angular/platform-browser-dynamic': '12.2.0',
			'@angular/router': '12.2.0',
			'rxjs': '6.6.0',
			'tslib': '2.3.0',
			'sass': '1.45.0',
			'zone.js': '0.11.4',
			'carbon-components-angular': '4.63.0',
			'carbon-components': '10.58.0'
		}
	};

	return {
		'src/index.html': format(indexHtml, formatOptionsHtml),
		'src/main.ts': format(mainTs, formatOptionsTypescript),
		'src/polyfills.ts': format("import 'zone.js/dist/zone';", formatOptionsTypescript),
		'src/styles.scss': format('', formatOptionsCss),
		'src/app/app.component.html': format(appComponentHtml, formatOptionsHtml),
		'src/app/app.component.ts': format(appComponentTs, formatOptionsTypescript),
		'src/app/app.module.ts': format(appModule, formatOptionsTypescript),
		...allComponents,
		'.angular-cli.json': angularCliJson,
		'package.json': packageJson
	};
};

// src/routes/edit/share-options/exports/frameworks/react/react-fragment.ts
import { sortedUniq } from 'lodash';
import { format as formatPrettier, Options } from 'prettier';
import parserBabel from 'prettier/parser-babel';
import parserCss from 'prettier/parser-postcss';
import { useContext } from 'react';
import { GlobalStateContext } from '../../../../../../context';
import { allComponents } from '../../../../../../fragment-components';
import { getAllFragmentStyleClasses } from '../../../../../../ui-fragment/src/utils';
import { classNameFromFragment, hasFragmentStyleClasses, tagNameFromFragment } from '../../../../../../utils/fragment-tools';

const format = (source: string, options?: Options | undefined) => {
	// we're catching and ignorring errors so live editing doesn't throw errors
	try {
		return formatPrettier(source, options);
	} catch (_) {
		return source;
	}
};

const formatOptions: Options = {
	plugins: [parserBabel],
	trailingComma: 'none',
	useTabs: true
};

const formatOptionsCss: Options = {
	parser: 'css',
	plugins: [parserCss]
};

const addIfNotExist = (arr: any[], items: any[]) => {
	items.forEach(item => {
		if (!arr.includes(item)) {
			arr.push(item);
		}
	});
	return arr;
};

const jsonToCarbonImports = (json: any) => {
	const imports: any[] = [];

	for (const component of Object.values(allComponents)) {
		if (json.type === component.componentInfo.type) {
			const componentImport = Array.isArray(component.componentInfo.codeExport.react.imports) ?
				component.componentInfo.codeExport.react.imports : component.componentInfo.codeExport.react.imports({ json });

			addIfNotExist(imports, componentImport);
		}
	}

	if (json.items) {
		json.items.forEach((item: any) => {
			addIfNotExist(imports, jsonToCarbonImports(item));
		});
	}

	return imports;
};

export const jsonToTemplate = (json: any, fragments: any[]) => {
	if (typeof json === 'string' || !json) {
		return json;
	}

	for (const component of Object.values(allComponents)) {
		if (json.type === component.componentInfo.type && !component.componentInfo.codeExport.react.isNotDirectExport) {
			return component.componentInfo.codeExport.react.code({ json, jsonToTemplate, fragments });
		}
	}

	if (json.items) {
		return json.items.map((item: any) => jsonToTemplate(item, fragments)).join('\n');
	}
};

export const getAdditionalCode = (componentObj: any, fragments: any[]) => {
	if (typeof componentObj === 'string' || !componentObj) {
		return componentObj;
	}
	let collectedCode = {};

	for (const component of Object.values(allComponents)) {
		if (componentObj.type === component.componentInfo.type && !component.componentInfo.codeExport.react.isNotDirectExport) {
			if (component.componentInfo.codeExport.react.additionalCode) {
				collectedCode = { ...collectedCode, ...component.componentInfo.codeExport.react.additionalCode(componentObj) };
			}
		}
	}

	if (componentObj.items) {
		componentObj.items.forEach((item: any) => {
			collectedCode = { ...collectedCode, ...getAdditionalCode(item, fragments) };
		});
	}

	return collectedCode;
};

const getAdditionalCodeAsString = (componentObj: any, fragments: any[]) => {
	const collectedCode = getAdditionalCode(componentObj, fragments);
	return Object.values(collectedCode).join('\n');
};

const otherImportsFromComponentObj = (json: any, fragments?: any[]) => {
	let imports = '';
	for (const component of Object.values(allComponents)) {
		if (json.type === component.componentInfo.type) {
			if (component.componentInfo.codeExport.react.otherImports) {
				imports += component.componentInfo.codeExport.react.otherImports({ json, fragments });
				break;
			}
		}
	}

	if (json.items) {
		imports += json.items.map((item: any) => otherImportsFromComponentObj(item, fragments)).join('\n');
	}

	// remove duplicate imports
	imports = sortedUniq(imports.split('\n')).join('\n');

	return imports;
};

const generateTemplate = (json: any, fragments: any[]) => {
	const carbonImports = jsonToCarbonImports(json);
	const carbonImportsString = carbonImports.reduce((string: string, curr: string) => (
		string += `${curr}, `
	), '');
	return {
		imports: `import { ${carbonImportsString} } from 'carbon-components-react';
			${otherImportsFromComponentObj(json, fragments)}`,
		template: jsonToTemplate(json, fragments),
		additionalCode: getAdditionalCodeAsString(json, fragments)
	};
};

const jsonToSharedComponents = (json: any, fragments: any[]) => {
	let sharedComponents: any = {};
	// eslint-disable-next-line react-hooks/rules-of-hooks
	const { styleClasses: globalStyleClasses } = useContext(GlobalStateContext);

	if (json.type === 'fragment') {
		const fragment = fragments.find(f => f.id === json.fragmentId);
		const fragmentTemplate = generateTemplate(fragment.data, fragments);

		sharedComponents[`src/shared/${tagNameFromFragment(fragment)}.js`] = format(`import React from 'react';
			${fragmentTemplate.imports};
			${hasFragmentStyleClasses(fragment) ? `
				import './${tagNameFromFragment(fragment)}.scss';
			` : ''}
			export const ${classNameFromFragment(fragment)} = ({state, setState}) => {
				const handleInputChange = (event) => {
					setState({...state, [event.target.name]: event.target.value});
				};

				${fragmentTemplate.additionalCode}

				return <>${fragmentTemplate.template}</>;
			};
		`, formatOptions);

		sharedComponents[`src/shared/${tagNameFromFragment(fragment)}.scss`] = format(
			`${getAllFragmentStyleClasses(fragment, [], globalStyleClasses).map((styleClass: any) => `.${styleClass.id} {
				${styleClass.content}
			}`).join('\n')}`,
			formatOptionsCss
		);

		sharedComponents = {
			...sharedComponents,
			...jsonToSharedComponents(fragment.data, fragments)
		};
	}

	json.items?.forEach((item: any) => {
		sharedComponents = {
			...sharedComponents,
			...jsonToSharedComponents(item, fragments)
		};
	});

	return sharedComponents;
};

export const createReactApp = (fragment: any, fragments: any[]) => {
	// eslint-disable-next-line react-hooks/rules-of-hooks
	const { styleClasses: globalStyleClasses } = useContext(GlobalStateContext);
	const fragmentTemplate = generateTemplate(fragment.data, fragments);

	const sharedComponents = jsonToSharedComponents(fragment.data, fragments);

	const indexHtml = `<div id='root'></div>
`;
	const componentJs
		= `import React from 'react';
${fragmentTemplate.imports};
${hasFragmentStyleClasses(fragment) ? "\nimport './component.scss';\n" : ''}
export const FragmentComponent = ({state, setState}) => {
	const handleInputChange = (event) => {
		setState({...state, [event.target.name]: event.target.value});
	};

	${fragmentTemplate.additionalCode}

	return <>${fragmentTemplate.template}</>;
};
`;

	const componentScss = getAllFragmentStyleClasses(fragment, [], globalStyleClasses).map((styleClass: any) => {
		if (!styleClass.content || !styleClass.content.trim()) {
			return null;
		}

		return `.${styleClass.id} {
			${styleClass.content}
		}`;
	}).join('\n');

	const indexJs
		= `import React, { useState } from 'react';
import ReactDOM from 'react-dom';

import 'carbon-components/css/carbon-components.css';

import { FragmentComponent } from './component.js';

const App = () => {
	const [state, setState] = useState({});

	return (
		<div>
			<FragmentComponent state={state} setState={setState} />
		</div>
	);
}
ReactDOM.render(<App />, document.getElementById('root'));
`;
	const packageJson = {
		dependencies: {
			'carbon-components': '10.58.0',
			'carbon-icons': '7.0.7',
			'@carbon/icons-react': '10.15.0',
			'carbon-components-react': '7.50.0',
			react: '16.12.0',
			'react-dom': '16.12.0',
			'react-scripts': '3.0.1',
			'sass': '1.45.0',
			emotion: '10.0.27'
		}
	};

	return {
		'src/index.html': indexHtml,
		'src/index.js': format(indexJs, formatOptions),
		'src/component.js': format(componentJs, formatOptions),
		'src/component.scss': format(componentScss, formatOptionsCss),
		'package.json': packageJson,
		...sharedComponents
	};
};
